name: Odoo Module Testing and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      # Test Module Structure
      - name: Test Module Structure
        run: bash testmodule.sh
        if: ${{ failure() }}

      # Linting with Ruff
      - name: Linting with Ruff
        run: python -m ruff check .

      # Test Inside Odoo Container
      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Start Docker Containers
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: docker-compose.yml
      - name: Run Odoo Tests Inside Container
        run: |
          docker-compose up -d
          docker exec -it odoo_container_name odoo-bin --test-tags wazzen --config /opt/bitnami/odoo/conf/test.conf
          docker-compose down
        env:
          odoo_container_name: "intern_odoo_1"
      - name: Cleanup Docker (optional)
        run: docker system prune -f

      # Envoyer une notification en cas d'échec
      - uses: github/notify@v2
        with:
          event_name: workflow_dispatch
          recipients: "your_email@example.com"
          message: "**ERREUR : Échec du workflow 'Odoo Module Testing and Linting'**"
        if: ${{ failure() }}
